// <auto-generated />
namespace platformy_NET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class trzeciapróba : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(trzeciapróba));
        
        string IMigrationMetadata.Id
        {
            get { return "202104181520479_trzecia-próba"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
